spring.application.name=auth-service

# Logs
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.sathwik.auth=DEBUG

server.tomcat.accesslog.enabled=true
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b

# DB (no password here)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

gemini.api.key = ${gemini_api_key}
gemini.api.model = ${gemini_model}

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

# OpenRouter
openrouter.api.key=${OPENROUTER_API_KEY}
openrouter.url=https://openrouter.ai/api/v1/chat/completions
